/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'rmolabanti' at '2/1/18 5:01 PM' with Gradle 2.6
 *
 * @author rmolabanti, @date 2/1/18 5:01 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
